name = "ArchCompStochasticModels"
uuid = "64888ec4-9db0-4860-a6f8-fd142b085b09"
authors = ["Frederik Baymler Mathiesen <frederik@baymler.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
