name = "ArchCompStochasticModels"
uuid = "64888ec4-9db0-4860-a6f8-fd142b085b09"
authors = ["Frederik Baymler Mathiesen <frederik@baymler.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LazySets = "3.1.0"
StaticArrays = "1.9.13"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
